// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loop_core.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const deleteLoopConfig = `-- name: DeleteLoopConfig :exec
DELETE FROM loop_config
WHERE workspace_id = ?1 AND loop_name = ?2
`

type DeleteLoopConfigParams struct {
	WorkspaceID string `json:"workspace_id"`
	LoopName    string `json:"loop_name"`
}

func (q *Queries) DeleteLoopConfig(ctx context.Context, arg DeleteLoopConfigParams) error {
	_, err := q.db.ExecContext(ctx, deleteLoopConfig, arg.WorkspaceID, arg.LoopName)
	return err
}

const deleteLoopUIAnnotations = `-- name: DeleteLoopUIAnnotations :exec
DELETE FROM loop_ui_annotations WHERE workspace_id = ?1 AND loop_name = ?2
`

type DeleteLoopUIAnnotationsParams struct {
	WorkspaceID string `json:"workspace_id"`
	LoopName    string `json:"loop_name"`
}

func (q *Queries) DeleteLoopUIAnnotations(ctx context.Context, arg DeleteLoopUIAnnotationsParams) error {
	_, err := q.db.ExecContext(ctx, deleteLoopUIAnnotations, arg.WorkspaceID, arg.LoopName)
	return err
}

const findActiveLoopRun = `-- name: FindActiveLoopRun :one
SELECT id, profile_id, workspace_id, loop_name, status, historical, completion_state, forked_from_run_id, forked_from_generation, generation, reattempt_strategy, last_progress_at, budget_tokens, budget_wall_sec, budget_on_exceeded, tokens_used, parent_loop_run_id, pause_requested, inputs_json, created_at, iteration_cap, started_by_kind, started_by_ref, started_origin_kind, started_origin_ref, started_at, definition_version, definition_digest, active_gate_id, active_human_criteria_json, budget_approval_seq, start_metadata_json, origin_kind, origin_session_id, goal_cleared_at, budget_version, goal_context_nudge_ratio, control_actor_kind, control_actor_id, control_requested_at, origin_creation_profile_ref, origin_policy_spec_digest, origin_creation_digest, network_spec_json, network_mode, network_channel, network_source, best_generation, best_score, cancel_requested, cancel_kind FROM loop_runs
WHERE workspace_id = ?1
  AND loop_name = ?2
  AND historical = 0
  AND status IN ('queued', 'running', 'watching', 'needs-approval', 'paused')
ORDER BY created_at ASC, id ASC
LIMIT 1
`

type FindActiveLoopRunParams struct {
	WorkspaceID string `json:"workspace_id"`
	LoopName    string `json:"loop_name"`
}

func (q *Queries) FindActiveLoopRun(ctx context.Context, arg FindActiveLoopRunParams) (LoopRun, error) {
	row := q.db.QueryRowContext(ctx, findActiveLoopRun, arg.WorkspaceID, arg.LoopName)
	var i LoopRun
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WorkspaceID,
		&i.LoopName,
		&i.Status,
		&i.Historical,
		&i.CompletionState,
		&i.ForkedFromRunID,
		&i.ForkedFromGeneration,
		&i.Generation,
		&i.ReattemptStrategy,
		&i.LastProgressAt,
		&i.BudgetTokens,
		&i.BudgetWallSec,
		&i.BudgetOnExceeded,
		&i.TokensUsed,
		&i.ParentLoopRunID,
		&i.PauseRequested,
		&i.InputsJson,
		&i.CreatedAt,
		&i.IterationCap,
		&i.StartedByKind,
		&i.StartedByRef,
		&i.StartedOriginKind,
		&i.StartedOriginRef,
		&i.StartedAt,
		&i.DefinitionVersion,
		&i.DefinitionDigest,
		&i.ActiveGateID,
		&i.ActiveHumanCriteriaJson,
		&i.BudgetApprovalSeq,
		&i.StartMetadataJson,
		&i.OriginKind,
		&i.OriginSessionID,
		&i.GoalClearedAt,
		&i.BudgetVersion,
		&i.GoalContextNudgeRatio,
		&i.ControlActorKind,
		&i.ControlActorID,
		&i.ControlRequestedAt,
		&i.OriginCreationProfileRef,
		&i.OriginPolicySpecDigest,
		&i.OriginCreationDigest,
		&i.NetworkSpecJson,
		&i.NetworkMode,
		&i.NetworkChannel,
		&i.NetworkSource,
		&i.BestGeneration,
		&i.BestScore,
		&i.CancelRequested,
		&i.CancelKind,
	)
	return i, err
}

const findLiveSessionGoal = `-- name: FindLiveSessionGoal :one
SELECT id, profile_id, workspace_id, loop_name, status, historical, completion_state, forked_from_run_id, forked_from_generation, generation, reattempt_strategy, last_progress_at, budget_tokens, budget_wall_sec, budget_on_exceeded, tokens_used, parent_loop_run_id, pause_requested, inputs_json, created_at, iteration_cap, started_by_kind, started_by_ref, started_origin_kind, started_origin_ref, started_at, definition_version, definition_digest, active_gate_id, active_human_criteria_json, budget_approval_seq, start_metadata_json, origin_kind, origin_session_id, goal_cleared_at, budget_version, goal_context_nudge_ratio, control_actor_kind, control_actor_id, control_requested_at, origin_creation_profile_ref, origin_policy_spec_digest, origin_creation_digest, network_spec_json, network_mode, network_channel, network_source, best_generation, best_score, cancel_requested, cancel_kind FROM loop_runs
WHERE workspace_id = ?1
  AND origin_kind = 'session'
  AND historical = 0
  AND origin_session_id = ?2
  AND status IN ('queued', 'running', 'watching', 'needs-approval', 'paused')
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type FindLiveSessionGoalParams struct {
	WorkspaceID     string         `json:"workspace_id"`
	OriginSessionID sql.NullString `json:"origin_session_id"`
}

func (q *Queries) FindLiveSessionGoal(ctx context.Context, arg FindLiveSessionGoalParams) (LoopRun, error) {
	row := q.db.QueryRowContext(ctx, findLiveSessionGoal, arg.WorkspaceID, arg.OriginSessionID)
	var i LoopRun
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WorkspaceID,
		&i.LoopName,
		&i.Status,
		&i.Historical,
		&i.CompletionState,
		&i.ForkedFromRunID,
		&i.ForkedFromGeneration,
		&i.Generation,
		&i.ReattemptStrategy,
		&i.LastProgressAt,
		&i.BudgetTokens,
		&i.BudgetWallSec,
		&i.BudgetOnExceeded,
		&i.TokensUsed,
		&i.ParentLoopRunID,
		&i.PauseRequested,
		&i.InputsJson,
		&i.CreatedAt,
		&i.IterationCap,
		&i.StartedByKind,
		&i.StartedByRef,
		&i.StartedOriginKind,
		&i.StartedOriginRef,
		&i.StartedAt,
		&i.DefinitionVersion,
		&i.DefinitionDigest,
		&i.ActiveGateID,
		&i.ActiveHumanCriteriaJson,
		&i.BudgetApprovalSeq,
		&i.StartMetadataJson,
		&i.OriginKind,
		&i.OriginSessionID,
		&i.GoalClearedAt,
		&i.BudgetVersion,
		&i.GoalContextNudgeRatio,
		&i.ControlActorKind,
		&i.ControlActorID,
		&i.ControlRequestedAt,
		&i.OriginCreationProfileRef,
		&i.OriginPolicySpecDigest,
		&i.OriginCreationDigest,
		&i.NetworkSpecJson,
		&i.NetworkMode,
		&i.NetworkChannel,
		&i.NetworkSource,
		&i.BestGeneration,
		&i.BestScore,
		&i.CancelRequested,
		&i.CancelKind,
	)
	return i, err
}

const findNewestSessionGoal = `-- name: FindNewestSessionGoal :one
SELECT id, goal_cleared_at
FROM loop_runs
WHERE workspace_id = ?1
  AND origin_kind = 'session'
  AND historical = 0
  AND origin_session_id = ?2
ORDER BY created_at DESC, rowid DESC
LIMIT 1
`

type FindNewestSessionGoalParams struct {
	WorkspaceID     string         `json:"workspace_id"`
	OriginSessionID sql.NullString `json:"origin_session_id"`
}

type FindNewestSessionGoalRow struct {
	ID            string       `json:"id"`
	GoalClearedAt sql.NullTime `json:"goal_cleared_at"`
}

func (q *Queries) FindNewestSessionGoal(ctx context.Context, arg FindNewestSessionGoalParams) (FindNewestSessionGoalRow, error) {
	row := q.db.QueryRowContext(ctx, findNewestSessionGoal, arg.WorkspaceID, arg.OriginSessionID)
	var i FindNewestSessionGoalRow
	err := row.Scan(&i.ID, &i.GoalClearedAt)
	return i, err
}

const getInlineGoalOriginSession = `-- name: GetInlineGoalOriginSession :one
SELECT workspace_id, state, creation_profile_ref, policy_spec_digest, creation_digest
FROM sessions WHERE id = ?1
`

type GetInlineGoalOriginSessionRow struct {
	WorkspaceID        string         `json:"workspace_id"`
	State              string         `json:"state"`
	CreationProfileRef sql.NullString `json:"creation_profile_ref"`
	PolicySpecDigest   sql.NullString `json:"policy_spec_digest"`
	CreationDigest     sql.NullString `json:"creation_digest"`
}

func (q *Queries) GetInlineGoalOriginSession(ctx context.Context, sessionID string) (GetInlineGoalOriginSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getInlineGoalOriginSession, sessionID)
	var i GetInlineGoalOriginSessionRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.State,
		&i.CreationProfileRef,
		&i.PolicySpecDigest,
		&i.CreationDigest,
	)
	return i, err
}

const getLoopConfig = `-- name: GetLoopConfig :one
SELECT human_gate_enabled, reattempt_strategy, enabled_checks_json,
       iteration_cap, budget_tokens, budget_wall_sec, budget_on_exceeded,
       no_progress_window, fan_out_width, gate_max_revisions,
       runtime_defaults_json, runtime_rules_json, environment_json, revision
FROM loop_config WHERE workspace_id = ?1 AND loop_name = ?2
`

type GetLoopConfigParams struct {
	WorkspaceID string `json:"workspace_id"`
	LoopName    string `json:"loop_name"`
}

type GetLoopConfigRow struct {
	HumanGateEnabled    int64          `json:"human_gate_enabled"`
	ReattemptStrategy   sql.NullString `json:"reattempt_strategy"`
	EnabledChecksJson   string         `json:"enabled_checks_json"`
	IterationCap        sql.NullInt64  `json:"iteration_cap"`
	BudgetTokens        sql.NullInt64  `json:"budget_tokens"`
	BudgetWallSec       sql.NullInt64  `json:"budget_wall_sec"`
	BudgetOnExceeded    sql.NullString `json:"budget_on_exceeded"`
	NoProgressWindow    sql.NullInt64  `json:"no_progress_window"`
	FanOutWidth         sql.NullInt64  `json:"fan_out_width"`
	GateMaxRevisions    sql.NullInt64  `json:"gate_max_revisions"`
	RuntimeDefaultsJson sql.NullString `json:"runtime_defaults_json"`
	RuntimeRulesJson    sql.NullString `json:"runtime_rules_json"`
	EnvironmentJson     sql.NullString `json:"environment_json"`
	Revision            int64          `json:"revision"`
}

func (q *Queries) GetLoopConfig(ctx context.Context, arg GetLoopConfigParams) (GetLoopConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getLoopConfig, arg.WorkspaceID, arg.LoopName)
	var i GetLoopConfigRow
	err := row.Scan(
		&i.HumanGateEnabled,
		&i.ReattemptStrategy,
		&i.EnabledChecksJson,
		&i.IterationCap,
		&i.BudgetTokens,
		&i.BudgetWallSec,
		&i.BudgetOnExceeded,
		&i.NoProgressWindow,
		&i.FanOutWidth,
		&i.GateMaxRevisions,
		&i.RuntimeDefaultsJson,
		&i.RuntimeRulesJson,
		&i.EnvironmentJson,
		&i.Revision,
	)
	return i, err
}

const getLoopRun = `-- name: GetLoopRun :one
SELECT id, profile_id, workspace_id, loop_name, status, historical, completion_state, forked_from_run_id, forked_from_generation, generation, reattempt_strategy, last_progress_at, budget_tokens, budget_wall_sec, budget_on_exceeded, tokens_used, parent_loop_run_id, pause_requested, inputs_json, created_at, iteration_cap, started_by_kind, started_by_ref, started_origin_kind, started_origin_ref, started_at, definition_version, definition_digest, active_gate_id, active_human_criteria_json, budget_approval_seq, start_metadata_json, origin_kind, origin_session_id, goal_cleared_at, budget_version, goal_context_nudge_ratio, control_actor_kind, control_actor_id, control_requested_at, origin_creation_profile_ref, origin_policy_spec_digest, origin_creation_digest, network_spec_json, network_mode, network_channel, network_source, best_generation, best_score, cancel_requested, cancel_kind FROM loop_runs WHERE workspace_id = ?1 AND id = ?2
`

type GetLoopRunParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetLoopRun(ctx context.Context, arg GetLoopRunParams) (LoopRun, error) {
	row := q.db.QueryRowContext(ctx, getLoopRun, arg.WorkspaceID, arg.ID)
	var i LoopRun
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WorkspaceID,
		&i.LoopName,
		&i.Status,
		&i.Historical,
		&i.CompletionState,
		&i.ForkedFromRunID,
		&i.ForkedFromGeneration,
		&i.Generation,
		&i.ReattemptStrategy,
		&i.LastProgressAt,
		&i.BudgetTokens,
		&i.BudgetWallSec,
		&i.BudgetOnExceeded,
		&i.TokensUsed,
		&i.ParentLoopRunID,
		&i.PauseRequested,
		&i.InputsJson,
		&i.CreatedAt,
		&i.IterationCap,
		&i.StartedByKind,
		&i.StartedByRef,
		&i.StartedOriginKind,
		&i.StartedOriginRef,
		&i.StartedAt,
		&i.DefinitionVersion,
		&i.DefinitionDigest,
		&i.ActiveGateID,
		&i.ActiveHumanCriteriaJson,
		&i.BudgetApprovalSeq,
		&i.StartMetadataJson,
		&i.OriginKind,
		&i.OriginSessionID,
		&i.GoalClearedAt,
		&i.BudgetVersion,
		&i.GoalContextNudgeRatio,
		&i.ControlActorKind,
		&i.ControlActorID,
		&i.ControlRequestedAt,
		&i.OriginCreationProfileRef,
		&i.OriginPolicySpecDigest,
		&i.OriginCreationDigest,
		&i.NetworkSpecJson,
		&i.NetworkMode,
		&i.NetworkChannel,
		&i.NetworkSource,
		&i.BestGeneration,
		&i.BestScore,
		&i.CancelRequested,
		&i.CancelKind,
	)
	return i, err
}

const getLoopRunByID = `-- name: GetLoopRunByID :one
SELECT id, profile_id, workspace_id, loop_name, status, historical, completion_state, forked_from_run_id, forked_from_generation, generation, reattempt_strategy, last_progress_at, budget_tokens, budget_wall_sec, budget_on_exceeded, tokens_used, parent_loop_run_id, pause_requested, inputs_json, created_at, iteration_cap, started_by_kind, started_by_ref, started_origin_kind, started_origin_ref, started_at, definition_version, definition_digest, active_gate_id, active_human_criteria_json, budget_approval_seq, start_metadata_json, origin_kind, origin_session_id, goal_cleared_at, budget_version, goal_context_nudge_ratio, control_actor_kind, control_actor_id, control_requested_at, origin_creation_profile_ref, origin_policy_spec_digest, origin_creation_digest, network_spec_json, network_mode, network_channel, network_source, best_generation, best_score, cancel_requested, cancel_kind FROM loop_runs WHERE id = ?1
`

func (q *Queries) GetLoopRunByID(ctx context.Context, id string) (LoopRun, error) {
	row := q.db.QueryRowContext(ctx, getLoopRunByID, id)
	var i LoopRun
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WorkspaceID,
		&i.LoopName,
		&i.Status,
		&i.Historical,
		&i.CompletionState,
		&i.ForkedFromRunID,
		&i.ForkedFromGeneration,
		&i.Generation,
		&i.ReattemptStrategy,
		&i.LastProgressAt,
		&i.BudgetTokens,
		&i.BudgetWallSec,
		&i.BudgetOnExceeded,
		&i.TokensUsed,
		&i.ParentLoopRunID,
		&i.PauseRequested,
		&i.InputsJson,
		&i.CreatedAt,
		&i.IterationCap,
		&i.StartedByKind,
		&i.StartedByRef,
		&i.StartedOriginKind,
		&i.StartedOriginRef,
		&i.StartedAt,
		&i.DefinitionVersion,
		&i.DefinitionDigest,
		&i.ActiveGateID,
		&i.ActiveHumanCriteriaJson,
		&i.BudgetApprovalSeq,
		&i.StartMetadataJson,
		&i.OriginKind,
		&i.OriginSessionID,
		&i.GoalClearedAt,
		&i.BudgetVersion,
		&i.GoalContextNudgeRatio,
		&i.ControlActorKind,
		&i.ControlActorID,
		&i.ControlRequestedAt,
		&i.OriginCreationProfileRef,
		&i.OriginPolicySpecDigest,
		&i.OriginCreationDigest,
		&i.NetworkSpecJson,
		&i.NetworkMode,
		&i.NetworkChannel,
		&i.NetworkSource,
		&i.BestGeneration,
		&i.BestScore,
		&i.CancelRequested,
		&i.CancelKind,
	)
	return i, err
}

const getLoopRunEventHead = `-- name: GetLoopRunEventHead :one
SELECT CAST(COALESCE(MAX(seq), 0) AS INTEGER)
FROM loop_run_events
WHERE workspace_id = ?1
  AND loop_run_id = ?2
`

type GetLoopRunEventHeadParams struct {
	WorkspaceID string `json:"workspace_id"`
	LoopRunID   string `json:"loop_run_id"`
}

func (q *Queries) GetLoopRunEventHead(ctx context.Context, arg GetLoopRunEventHeadParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLoopRunEventHead, arg.WorkspaceID, arg.LoopRunID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertLoopConfig = `-- name: InsertLoopConfig :exec
INSERT INTO loop_config (
  workspace_id, loop_name, human_gate_enabled, reattempt_strategy, enabled_checks_json,
  iteration_cap, budget_tokens, budget_wall_sec, budget_on_exceeded,
  no_progress_window, fan_out_width, gate_max_revisions,
  runtime_defaults_json, runtime_rules_json, environment_json, revision
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5, ?6,
  ?7, ?8, ?9,
  ?10, ?11, ?12,
  ?13, ?14, ?15,
  ?16
)
`

type InsertLoopConfigParams struct {
	WorkspaceID         string         `json:"workspace_id"`
	LoopName            string         `json:"loop_name"`
	HumanGateEnabled    int64          `json:"human_gate_enabled"`
	ReattemptStrategy   sql.NullString `json:"reattempt_strategy"`
	EnabledChecksJson   string         `json:"enabled_checks_json"`
	IterationCap        sql.NullInt64  `json:"iteration_cap"`
	BudgetTokens        sql.NullInt64  `json:"budget_tokens"`
	BudgetWallSec       sql.NullInt64  `json:"budget_wall_sec"`
	BudgetOnExceeded    sql.NullString `json:"budget_on_exceeded"`
	NoProgressWindow    sql.NullInt64  `json:"no_progress_window"`
	FanOutWidth         sql.NullInt64  `json:"fan_out_width"`
	GateMaxRevisions    sql.NullInt64  `json:"gate_max_revisions"`
	RuntimeDefaultsJson sql.NullString `json:"runtime_defaults_json"`
	RuntimeRulesJson    sql.NullString `json:"runtime_rules_json"`
	EnvironmentJson     sql.NullString `json:"environment_json"`
	Revision            int64          `json:"revision"`
}

func (q *Queries) InsertLoopConfig(ctx context.Context, arg InsertLoopConfigParams) error {
	_, err := q.db.ExecContext(ctx, insertLoopConfig,
		arg.WorkspaceID,
		arg.LoopName,
		arg.HumanGateEnabled,
		arg.ReattemptStrategy,
		arg.EnabledChecksJson,
		arg.IterationCap,
		arg.BudgetTokens,
		arg.BudgetWallSec,
		arg.BudgetOnExceeded,
		arg.NoProgressWindow,
		arg.FanOutWidth,
		arg.GateMaxRevisions,
		arg.RuntimeDefaultsJson,
		arg.RuntimeRulesJson,
		arg.EnvironmentJson,
		arg.Revision,
	)
	return err
}

const insertLoopRun = `-- name: InsertLoopRun :exec
INSERT INTO loop_runs (
  profile_id,
  id, workspace_id, loop_name, status, historical, generation, reattempt_strategy, created_at, started_at,
  last_progress_at, definition_version, definition_digest, active_gate_id,
  active_human_criteria_json, budget_approval_seq, start_metadata_json,
  iteration_cap, budget_tokens, budget_wall_sec,
  budget_on_exceeded, tokens_used, parent_loop_run_id, pause_requested, inputs_json,
  started_by_kind, started_by_ref, started_origin_kind, started_origin_ref,
  goal_context_nudge_ratio, origin_kind, origin_session_id,
  origin_creation_profile_ref, origin_policy_spec_digest, origin_creation_digest,
  network_spec_json, network_mode, network_channel, network_source
) VALUES (
  ?1,
  ?2, ?3, ?4, ?5, ?6,
  ?7, ?8, ?9, ?10,
  ?11, ?12, ?13,
  ?14, ?15, ?16,
  ?17, ?18,
  ?19, ?20, ?21,
  ?22, ?23, ?24,
  ?25, ?26, ?27,
  ?28, ?29, ?30,
  ?31, ?32, ?33,
  ?34, ?35,
  ?36, ?37, ?38,
  ?39
)
`

type InsertLoopRunParams struct {
	ProfileID                string         `json:"profile_id"`
	ID                       string         `json:"id"`
	WorkspaceID              string         `json:"workspace_id"`
	LoopName                 string         `json:"loop_name"`
	Status                   string         `json:"status"`
	Historical               int64          `json:"historical"`
	Generation               int64          `json:"generation"`
	ReattemptStrategy        string         `json:"reattempt_strategy"`
	CreatedAt                string         `json:"created_at"`
	StartedAt                string         `json:"started_at"`
	LastProgressAt           time.Time      `json:"last_progress_at"`
	DefinitionVersion        int64          `json:"definition_version"`
	DefinitionDigest         string         `json:"definition_digest"`
	ActiveGateID             string         `json:"active_gate_id"`
	ActiveHumanCriteriaJson  string         `json:"active_human_criteria_json"`
	BudgetApprovalSeq        int64          `json:"budget_approval_seq"`
	StartMetadataJson        string         `json:"start_metadata_json"`
	IterationCap             int64          `json:"iteration_cap"`
	BudgetTokens             int64          `json:"budget_tokens"`
	BudgetWallSec            int64          `json:"budget_wall_sec"`
	BudgetOnExceeded         string         `json:"budget_on_exceeded"`
	TokensUsed               int64          `json:"tokens_used"`
	ParentLoopRunID          sql.NullString `json:"parent_loop_run_id"`
	PauseRequested           int64          `json:"pause_requested"`
	InputsJson               string         `json:"inputs_json"`
	StartedByKind            string         `json:"started_by_kind"`
	StartedByRef             string         `json:"started_by_ref"`
	StartedOriginKind        string         `json:"started_origin_kind"`
	StartedOriginRef         string         `json:"started_origin_ref"`
	GoalContextNudgeRatio    float64        `json:"goal_context_nudge_ratio"`
	OriginKind               string         `json:"origin_kind"`
	OriginSessionID          sql.NullString `json:"origin_session_id"`
	OriginCreationProfileRef sql.NullString `json:"origin_creation_profile_ref"`
	OriginPolicySpecDigest   sql.NullString `json:"origin_policy_spec_digest"`
	OriginCreationDigest     sql.NullString `json:"origin_creation_digest"`
	NetworkSpecJson          string         `json:"network_spec_json"`
	NetworkMode              string         `json:"network_mode"`
	NetworkChannel           sql.NullString `json:"network_channel"`
	NetworkSource            string         `json:"network_source"`
}

func (q *Queries) InsertLoopRun(ctx context.Context, arg InsertLoopRunParams) error {
	_, err := q.db.ExecContext(ctx, insertLoopRun,
		arg.ProfileID,
		arg.ID,
		arg.WorkspaceID,
		arg.LoopName,
		arg.Status,
		arg.Historical,
		arg.Generation,
		arg.ReattemptStrategy,
		arg.CreatedAt,
		arg.StartedAt,
		arg.LastProgressAt,
		arg.DefinitionVersion,
		arg.DefinitionDigest,
		arg.ActiveGateID,
		arg.ActiveHumanCriteriaJson,
		arg.BudgetApprovalSeq,
		arg.StartMetadataJson,
		arg.IterationCap,
		arg.BudgetTokens,
		arg.BudgetWallSec,
		arg.BudgetOnExceeded,
		arg.TokensUsed,
		arg.ParentLoopRunID,
		arg.PauseRequested,
		arg.InputsJson,
		arg.StartedByKind,
		arg.StartedByRef,
		arg.StartedOriginKind,
		arg.StartedOriginRef,
		arg.GoalContextNudgeRatio,
		arg.OriginKind,
		arg.OriginSessionID,
		arg.OriginCreationProfileRef,
		arg.OriginPolicySpecDigest,
		arg.OriginCreationDigest,
		arg.NetworkSpecJson,
		arg.NetworkMode,
		arg.NetworkChannel,
		arg.NetworkSource,
	)
	return err
}

const insertLoopRunEvent = `-- name: InsertLoopRunEvent :exec
INSERT INTO loop_run_events (id, loop_run_id, workspace_id, seq, kind, payload_json, at)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6, ?7)
`

type InsertLoopRunEventParams struct {
	ID          string    `json:"id"`
	LoopRunID   string    `json:"loop_run_id"`
	WorkspaceID string    `json:"workspace_id"`
	Seq         int64     `json:"seq"`
	Kind        string    `json:"kind"`
	PayloadJson string    `json:"payload_json"`
	At          time.Time `json:"at"`
}

func (q *Queries) InsertLoopRunEvent(ctx context.Context, arg InsertLoopRunEventParams) error {
	_, err := q.db.ExecContext(ctx, insertLoopRunEvent,
		arg.ID,
		arg.LoopRunID,
		arg.WorkspaceID,
		arg.Seq,
		arg.Kind,
		arg.PayloadJson,
		arg.At,
	)
	return err
}

const insertLoopUIAnnotation = `-- name: InsertLoopUIAnnotation :exec
INSERT INTO loop_ui_annotations (workspace_id, loop_name, node_id, x, y)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertLoopUIAnnotationParams struct {
	WorkspaceID string  `json:"workspace_id"`
	LoopName    string  `json:"loop_name"`
	NodeID      string  `json:"node_id"`
	X           float64 `json:"x"`
	Y           float64 `json:"y"`
}

func (q *Queries) InsertLoopUIAnnotation(ctx context.Context, arg InsertLoopUIAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, insertLoopUIAnnotation,
		arg.WorkspaceID,
		arg.LoopName,
		arg.NodeID,
		arg.X,
		arg.Y,
	)
	return err
}

const listLoopRouteCauses = `-- name: ListLoopRouteCauses :many
SELECT payload_json, at
FROM loop_run_events
WHERE workspace_id = ?1
  AND loop_run_id = ?2
  AND kind = 'route_taken'
  AND CAST(json_extract(payload_json, '$.generation') AS INTEGER) = ?3
ORDER BY seq ASC
`

type ListLoopRouteCausesParams struct {
	WorkspaceID string `json:"workspace_id"`
	LoopRunID   string `json:"loop_run_id"`
	Generation  string `json:"generation"`
}

type ListLoopRouteCausesRow struct {
	PayloadJson string    `json:"payload_json"`
	At          time.Time `json:"at"`
}

func (q *Queries) ListLoopRouteCauses(ctx context.Context, arg ListLoopRouteCausesParams) ([]ListLoopRouteCausesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLoopRouteCauses, arg.WorkspaceID, arg.LoopRunID, arg.Generation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoopRouteCausesRow{}
	for rows.Next() {
		var i ListLoopRouteCausesRow
		if err := rows.Scan(&i.PayloadJson, &i.At); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoopRunEvents = `-- name: ListLoopRunEvents :many
SELECT watch_seq, id, loop_run_id, workspace_id, seq, kind, payload_json, at, delivery_key
FROM loop_run_events
WHERE workspace_id = ?1
  AND loop_run_id = ?2
  AND seq > ?3
ORDER BY seq ASC
LIMIT ?4
`

type ListLoopRunEventsParams struct {
	WorkspaceID string `json:"workspace_id"`
	LoopRunID   string `json:"loop_run_id"`
	AfterSeq    int64  `json:"after_seq"`
	RowLimit    int64  `json:"row_limit"`
}

func (q *Queries) ListLoopRunEvents(ctx context.Context, arg ListLoopRunEventsParams) ([]LoopRunEvent, error) {
	rows, err := q.db.QueryContext(ctx, listLoopRunEvents,
		arg.WorkspaceID,
		arg.LoopRunID,
		arg.AfterSeq,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoopRunEvent{}
	for rows.Next() {
		var i LoopRunEvent
		if err := rows.Scan(
			&i.WatchSeq,
			&i.ID,
			&i.LoopRunID,
			&i.WorkspaceID,
			&i.Seq,
			&i.Kind,
			&i.PayloadJson,
			&i.At,
			&i.DeliveryKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoopRunEventsBackward = `-- name: ListLoopRunEventsBackward :many
SELECT watch_seq, id, loop_run_id, workspace_id, seq, kind, payload_json, at, delivery_key
FROM loop_run_events
WHERE workspace_id = ?1
  AND loop_run_id = ?2
  AND seq <= ?3
  AND seq < ?4
ORDER BY seq DESC
LIMIT ?5
`

type ListLoopRunEventsBackwardParams struct {
	WorkspaceID  string `json:"workspace_id"`
	LoopRunID    string `json:"loop_run_id"`
	FixedHeadSeq int64  `json:"fixed_head_seq"`
	BeforeSeq    int64  `json:"before_seq"`
	RowLimit     int64  `json:"row_limit"`
}

func (q *Queries) ListLoopRunEventsBackward(ctx context.Context, arg ListLoopRunEventsBackwardParams) ([]LoopRunEvent, error) {
	rows, err := q.db.QueryContext(ctx, listLoopRunEventsBackward,
		arg.WorkspaceID,
		arg.LoopRunID,
		arg.FixedHeadSeq,
		arg.BeforeSeq,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoopRunEvent{}
	for rows.Next() {
		var i LoopRunEvent
		if err := rows.Scan(
			&i.WatchSeq,
			&i.ID,
			&i.LoopRunID,
			&i.WorkspaceID,
			&i.Seq,
			&i.Kind,
			&i.PayloadJson,
			&i.At,
			&i.DeliveryKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoopUIAnnotations = `-- name: ListLoopUIAnnotations :many
SELECT node_id, x, y FROM loop_ui_annotations
WHERE workspace_id = ?1 AND loop_name = ?2
ORDER BY node_id ASC
`

type ListLoopUIAnnotationsParams struct {
	WorkspaceID string `json:"workspace_id"`
	LoopName    string `json:"loop_name"`
}

type ListLoopUIAnnotationsRow struct {
	NodeID string  `json:"node_id"`
	X      float64 `json:"x"`
	Y      float64 `json:"y"`
}

func (q *Queries) ListLoopUIAnnotations(ctx context.Context, arg ListLoopUIAnnotationsParams) ([]ListLoopUIAnnotationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLoopUIAnnotations, arg.WorkspaceID, arg.LoopName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoopUIAnnotationsRow{}
	for rows.Next() {
		var i ListLoopUIAnnotationsRow
		if err := rows.Scan(&i.NodeID, &i.X, &i.Y); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInlineGoalRunCleared = `-- name: MarkInlineGoalRunCleared :execrows
UPDATE loop_runs SET goal_cleared_at = ?1
WHERE id = ?2 AND workspace_id = ?3 AND goal_cleared_at IS NULL
`

type MarkInlineGoalRunClearedParams struct {
	GoalClearedAt sql.NullTime `json:"goal_cleared_at"`
	ID            string       `json:"id"`
	WorkspaceID   string       `json:"workspace_id"`
}

func (q *Queries) MarkInlineGoalRunCleared(ctx context.Context, arg MarkInlineGoalRunClearedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markInlineGoalRunCleared, arg.GoalClearedAt, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const nextLoopRunEventSequence = `-- name: NextLoopRunEventSequence :one
SELECT COALESCE(MAX(seq), 0) + 1 FROM loop_run_events WHERE loop_run_id = ?1
`

func (q *Queries) NextLoopRunEventSequence(ctx context.Context, loopRunID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextLoopRunEventSequence, loopRunID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const replaceLoopConfig = `-- name: ReplaceLoopConfig :exec
UPDATE loop_config SET
  human_gate_enabled = ?1,
  reattempt_strategy = ?2,
  enabled_checks_json = ?3,
  iteration_cap = ?4,
  budget_tokens = ?5,
  budget_wall_sec = ?6,
  budget_on_exceeded = ?7,
  no_progress_window = ?8,
  fan_out_width = ?9,
  gate_max_revisions = ?10,
  runtime_defaults_json = ?11,
  runtime_rules_json = ?12,
  environment_json = ?13,
  revision = ?14
WHERE workspace_id = ?15 AND loop_name = ?16
`

type ReplaceLoopConfigParams struct {
	HumanGateEnabled    int64          `json:"human_gate_enabled"`
	ReattemptStrategy   sql.NullString `json:"reattempt_strategy"`
	EnabledChecksJson   string         `json:"enabled_checks_json"`
	IterationCap        sql.NullInt64  `json:"iteration_cap"`
	BudgetTokens        sql.NullInt64  `json:"budget_tokens"`
	BudgetWallSec       sql.NullInt64  `json:"budget_wall_sec"`
	BudgetOnExceeded    sql.NullString `json:"budget_on_exceeded"`
	NoProgressWindow    sql.NullInt64  `json:"no_progress_window"`
	FanOutWidth         sql.NullInt64  `json:"fan_out_width"`
	GateMaxRevisions    sql.NullInt64  `json:"gate_max_revisions"`
	RuntimeDefaultsJson sql.NullString `json:"runtime_defaults_json"`
	RuntimeRulesJson    sql.NullString `json:"runtime_rules_json"`
	EnvironmentJson     sql.NullString `json:"environment_json"`
	Revision            int64          `json:"revision"`
	WorkspaceID         string         `json:"workspace_id"`
	LoopName            string         `json:"loop_name"`
}

func (q *Queries) ReplaceLoopConfig(ctx context.Context, arg ReplaceLoopConfigParams) error {
	_, err := q.db.ExecContext(ctx, replaceLoopConfig,
		arg.HumanGateEnabled,
		arg.ReattemptStrategy,
		arg.EnabledChecksJson,
		arg.IterationCap,
		arg.BudgetTokens,
		arg.BudgetWallSec,
		arg.BudgetOnExceeded,
		arg.NoProgressWindow,
		arg.FanOutWidth,
		arg.GateMaxRevisions,
		arg.RuntimeDefaultsJson,
		arg.RuntimeRulesJson,
		arg.EnvironmentJson,
		arg.Revision,
		arg.WorkspaceID,
		arg.LoopName,
	)
	return err
}
