// Code generated by go run ./cmd/compozy-codegen sdk-contracts-go. DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
)

type DeliveryErrorDetail struct {
	Message string `json:"message"`
}

type DeliveryEvent struct {
	DeliveryID       string                    `json:"delivery_id"`
	BridgeInstanceID string                    `json:"bridge_instance_id"`
	RoutingKey       RoutingKey                `json:"routing_key"`
	DeliveryTarget   DeliveryTarget            `json:"delivery_target"`
	Seq              int64                     `json:"seq"`
	EventType        DeliveryEventType         `json:"event_type"`
	Content          MessageContent            `json:"content"`
	Final            bool                      `json:"final"`
	Operation        DeliveryOperation         `json:"operation,omitempty"`
	Reference        *DeliveryMessageReference `json:"reference,omitempty"`
	Error            *DeliveryErrorDetail      `json:"error,omitempty"`
	Resume           *DeliveryResumeState      `json:"resume,omitempty"`
	Progress         *ToolProgress             `json:"progress,omitempty"`
	ProviderMetadata json.RawMessage           `json:"provider_metadata,omitempty"`
}

type DeliveryEventType string

type DeliveryMessageReference struct {
	DeliveryID      string `json:"delivery_id,omitempty"`
	RemoteMessageID string `json:"remote_message_id,omitempty"`
}

type DeliveryMode string

type DeliveryOperation string

type DeliveryRequest struct {
	Event    DeliveryEvent     `json:"event"`
	Snapshot *DeliverySnapshot `json:"snapshot,omitempty"`
}

type DeliveryResumeState struct {
	LatestEventType DeliveryEventType `json:"latest_event_type"`
}

type DeliverySnapshot struct {
	DeliveryID             string                    `json:"delivery_id"`
	SessionID              string                    `json:"session_id"`
	TurnID                 string                    `json:"turn_id"`
	BridgeInstanceID       string                    `json:"bridge_instance_id"`
	RoutingKey             RoutingKey                `json:"routing_key"`
	DeliveryTarget         DeliveryTarget            `json:"delivery_target"`
	LatestSeq              int64                     `json:"latest_seq"`
	LatestEventType        DeliveryEventType         `json:"latest_event_type"`
	CurrentContent         MessageContent            `json:"current_content"`
	Operation              DeliveryOperation         `json:"operation,omitempty"`
	Reference              *DeliveryMessageReference `json:"reference,omitempty"`
	ProviderMetadata       json.RawMessage           `json:"provider_metadata,omitempty"`
	LastSentSeq            int64                     `json:"last_sent_seq,omitempty"`
	LastAckedSeq           int64                     `json:"last_acked_seq,omitempty"`
	RemoteMessageID        string                    `json:"remote_message_id,omitempty"`
	ReplaceRemoteMessageID string                    `json:"replace_remote_message_id,omitempty"`
	Final                  bool                      `json:"final"`
	Error                  string                    `json:"error,omitempty"`
	UpdatedAt              time.Time                 `json:"updated_at"`
}

type DeliveryTarget struct {
	BridgeInstanceID string       `json:"bridge_instance_id"`
	PeerID           string       `json:"peer_id,omitempty"`
	ThreadID         string       `json:"thread_id,omitempty"`
	GroupID          string       `json:"group_id,omitempty"`
	Mode             DeliveryMode `json:"mode,omitempty"`
}

type DependencyKind string

type DescribeHookEvent struct {
	Name     string      `json:"name,omitempty"`
	Event    HookEvent   `json:"event"`
	Profile  string      `json:"profile,omitempty"`
	Mode     HookMode    `json:"mode,omitempty"`
	Matcher  HookMatcher `json:"matcher,omitzero"`
	Required bool        `json:"required,omitempty"`
}

type DescribeNetworkParticipation struct {
	Required      bool     `json:"required"`
	Mode          string   `json:"mode"`
	ChannelScopes []string `json:"channel_scopes,omitempty"`
}

type DescribePayload struct {
	Name                 string                           `json:"name"`
	Version              string                           `json:"version"`
	Description          string                           `json:"description,omitempty"`
	Provides             []string                         `json:"provides"`
	Permissions          []string                         `json:"permissions"`
	RequiresEnv          []string                         `json:"requires_env,omitempty"`
	Profiles             []DescribeProfile                `json:"profiles,omitempty"`
	Resources            DescribeResources                `json:"resources"`
	Subprocess           DescribeSubprocess               `json:"subprocess"`
	NetworkParticipation *DescribeNetworkParticipation    `json:"network_participation,omitempty"`
	Tools                []ExtensionToolRuntimeDescriptor `json:"tools,omitempty"`
	HookEvents           []DescribeHookEvent              `json:"hook_events,omitempty"`
	WatchSourceKinds     []string                         `json:"watch_source_kinds,omitempty"`
	CmdPaletteViews      []string                         `json:"cmd_palette_views,omitempty"`
	CommandGroups        []ExtensionCommandGroupSpec      `json:"command_groups,omitempty"`
	SDK                  DescribeSDKInfo                  `json:"sdk"`
}

type DescribeProfile struct {
	Name        string                      `json:"name"`
	Color       string                      `json:"color,omitempty"`
	Icon        string                      `json:"icon,omitempty"`
	Emoji       string                      `json:"emoji,omitempty"`
	Defaults    DescribeProfileDefaults     `json:"defaults,omitzero"`
	Credentials []DescribeProfileCredential `json:"credentials,omitempty"`
}

type DescribeProfileCredential struct {
	Provider string `json:"provider"`
	Slot     string `json:"slot"`
}

type DescribeProfileDefaults struct {
	Agent    string `json:"agent,omitempty"`
	Provider string `json:"provider,omitempty"`
	Sandbox  string `json:"sandbox,omitempty"`
}

type DescribeResourcePath struct {
	Path    string `json:"path"`
	Profile string `json:"profile,omitempty"`
}

type DescribeResources struct {
	Skills     []DescribeResourcePath `json:"skills,omitempty"`
	Loops      []DescribeResourcePath `json:"loops,omitempty"`
	Agents     []DescribeResourcePath `json:"agents,omitempty"`
	Automation []DescribeResourcePath `json:"automation,omitempty"`
	Layouts    []DescribeResourcePath `json:"layouts,omitempty"`
	CmdPalette CmdPaletteConfig       `json:"cmd_palette,omitzero"`
}

type DescribeSDKInfo struct {
	Name              string `json:"name"`
	Version           string `json:"version"`
	ProtocolVersion   string `json:"protocol_version"`
	MinCompozyVersion string `json:"min_compozy_version"`
}

type DescribeSubprocess struct {
	Command string            `json:"command"`
	Args    []string          `json:"args,omitempty"`
	Env     map[string]string `json:"env,omitempty"`
}

type DetailBody struct {
	IsLoading bool        `json:"is_loading,omitempty"`
	Markdown  string      `json:"markdown,omitempty"`
	Metadata  []MetaField `json:"metadata,omitempty"`
	Actions   []RowAction `json:"actions,omitempty"`
}

type Effect struct {
	ID        string           `json:"id"`
	Toast     *ToastEffect     `json:"toast,omitempty"`
	Copy      *CopyEffect      `json:"copy,omitempty"`
	OpenURL   *OpenURLEffect   `json:"open_url,omitempty"`
	OpenApp   *OpenAppEffect   `json:"open_app,omitempty"`
	PickFiles *PickFilesEffect `json:"pick_files,omitempty"`
}

type EffectResult struct {
	EffectID string          `json:"effect_id"`
	Payload  json.RawMessage `json:"payload,omitempty"`
}
